package org.usfirst.frc811.RobotCode2015.commands;

import org.usfirst.frc811.RobotCode2015.Config;
import org.usfirst.frc811.RobotCode2015.Robot;
import org.usfirst.frc811.RobotCode2015.RobotMap;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

public class lift_encoder_reset extends Command implements Config {
	
	public lift_encoder_reset() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.lift);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	SmartDashboard.putString("lift encoder reset status", "about to reset");
    	Robot.lift.encoderReset();
    	SmartDashboard.putString("lift encoder reset status", "just reset");
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	SmartDashboard.putBoolean("limit switches", (RobotMap.liftTalon_Left.isFwdLimitSwitchClosed() && RobotMap.liftTalon_Right.isFwdLimitSwitchClosed()));
    	return (RobotMap.liftTalon_Left.isFwdLimitSwitchClosed() && RobotMap.liftTalon_Right.isFwdLimitSwitchClosed());
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.lift.encoderResetDone();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }

}
