// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc811.RobotCode2015.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc811.RobotCode2015.Config;

public class  preset extends CommandGroup implements Config {

    public preset() 
    {
    	addSequential(new lift_encoder_reset());
    	addSequential(new arm_to_preload());
    	addSequential(new lift_to_preload());
    }
}