// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc811.RobotCode2015;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.command.CommandGroup;

import org.usfirst.frc811.RobotCode2015.commands.*;
import org.usfirst.frc811.RobotCode2015.subsystems.*;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot implements Config {

    Command autonomousCommand;
    SendableChooser autoChooser;
    
    

    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Drive drive;
    public static Lift lift;
    public static Claw claw;
    public static Arm arm;
    public static Kicker kick;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    	RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	drive = new Drive();
        lift = new Lift();
        claw = new Claw();
        arm = new Arm();
        kick = new Kicker();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands 
        //(which it very likely will), subsystems are not guaranteed to be 
        // constructed yet. Thus, their requires() statements may grab null 
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        	//autonomousCommand = new AutonomousCommand();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        autoChooser = new SendableChooser();
        autoChooser.addDefault("Just drive", new drive_auto(-17));
        autoChooser.addObject("Three Totes", new ThreeToteAuto());
        autoChooser.addObject("Two Totes", new TwoToteAuto());
        autoChooser.addObject("One Tote", new OneToteAuto());
        autoChooser.addObject("Three Totes v2", new ThreeToteAutov2());
        SmartDashboard.putData("Auto Mode", autoChooser);
        
    }

    
    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {    	 
        // schedule the autonomous command (example)
        //if (autonomousCommand != null) autonomousCommand.start();
    	//Robot.lift.encoderReset();
    	RobotMap.driveGyro1.reset();
    	autonomousCommand = (Command) autoChooser.getSelected();
		autonomousCommand.start();
		
       

    	
        
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    /*	
    	RobotMap.liftTalon_Right.changeControlMode(CANTalon.ControlMode.PercentVbus);
        RobotMap.liftTalon_Left.changeControlMode(CANTalon.ControlMode.PercentVbus);
        RobotMap.armarm_talon.changeControlMode(CANTalon.ControlMode.PercentVbus);
        RobotMap.liftTalon_Left.enableLimitSwitch(true, true);
        RobotMap.liftTalon_Right.enableLimitSwitch(true, true);
        //RobotMap.liftTalon_Right.set(0.2);
        //RobotMap.liftTalon_Left.set(0.2);
        //RobotMap.armarm_talon.set(0.2);
       // RobotMap.drivebackleft.set(0.2);
       // RobotMap.drivebackright.set(0.2);
       // RobotMap.drivefrontleft.set(0.2);
       // RobotMap.drivefrontright.set(0.2);
        
        SmartDashboard.putBoolean("left forward limit", RobotMap.liftTalon_Left.isFwdLimitSwitchClosed());
        SmartDashboard.putBoolean("left reverse limit", RobotMap.liftTalon_Left.isRevLimitSwitchClosed());
        SmartDashboard.putBoolean("right forward limit", RobotMap.liftTalon_Right.isFwdLimitSwitchClosed());
        SmartDashboard.putBoolean("right reverse limit", RobotMap.liftTalon_Right.isRevLimitSwitchClosed());
        
        SmartDashboard.putNumber("pot value", RobotMap.armarm_talon.getAnalogInRaw());
        SmartDashboard.putNumber("gyro value", RobotMap.driveGyro1.getAngle());        
        SmartDashboard.putNumber("auto encoder value", RobotMap.drivedrive_encoder.getDistance());
        SmartDashboard.putNumber("lift left talon value", RobotMap.liftTalon_Left.getEncPosition());
    	SmartDashboard.putNumber("lift right talon value", RobotMap.liftTalon_Right.getEncPosition());
    	*/
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to 
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        RobotMap.drivedrive_encoder.reset();
        RobotMap.drivedrive_encoder.setDistancePerPulse(1/14.5);
        RobotMap.drivedrive_encoder.setReverseDirection(true);
        RobotMap.driveGyro1.reset();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
    	
        Scheduler.getInstance().run();
        
        //smart dashboard inputs here
        //SmartDashboard.putNumber("pot value", RobotMap.armarm_talon.get());
        SmartDashboard.putNumber("gyro value", RobotMap.driveGyro1.getAngle());        
        SmartDashboard.putNumber("encoder of the drive train value", RobotMap.drivedrive_encoder.getDistance());
    	SmartDashboard.putNumber("lift left encoder value", RobotMap.liftTalon_Left.getEncPosition());
    	SmartDashboard.putNumber("lift right encoder value", RobotMap.liftTalon_Right.getEncPosition());
    	SmartDashboard.putNumber("arm joystick value", RobotMap.joystick2.getRawAxis(ARM_MOVEMENT_JOYSTICK_AXIS));
    	SmartDashboard.putNumber("lift up joystick value", RobotMap.joystick2.getRawAxis(LIFT_UP_JOYSTICK_AXIS));
    	SmartDashboard.putNumber("lift down joystick value", RobotMap.joystick2.getRawAxis(LIFT_DOWN_JOYSTICK_AXIS));
    	SmartDashboard.putBoolean("reset button", RobotMap.joystick2.getRawButton(LIFT_ENCODER_RESET_BUTTON));
    	SmartDashboard.putNumber("lift left error", RobotMap.liftTalon_Left.getClosedLoopError());
    	SmartDashboard.putNumber("lift right error", RobotMap.liftTalon_Right.getClosedLoopError());
    	
    	//camera displayed to the smart dashboard
    	CameraServer cam = CameraServer.getInstance();
    	cam.setQuality(50);
    	cam.startAutomaticCapture("cam0");
    }

    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
        RobotMap.liftTalon_Right.changeControlMode(CANTalon.ControlMode.PercentVbus);
        RobotMap.liftTalon_Left.changeControlMode(CANTalon.ControlMode.PercentVbus);
        RobotMap.liftTalon_Right.reverseOutput(true);
        RobotMap.liftTalon_Left.reverseOutput(true);
        RobotMap.liftTalon_Left.enableLimitSwitch(true, true);
        RobotMap.liftTalon_Right.enableLimitSwitch(true, true);
        //RobotMap.liftTalon_Right.set(0.2);
        //RobotMap.liftTalon_Left.set(0.2);
        
        SmartDashboard.putBoolean("left forward limit", RobotMap.liftTalon_Left.isFwdLimitSwitchClosed());
        SmartDashboard.putBoolean("left reverse limit", RobotMap.liftTalon_Left.isRevLimitSwitchClosed());
        SmartDashboard.putBoolean("right forward limit", RobotMap.liftTalon_Right.isFwdLimitSwitchClosed());
        SmartDashboard.putBoolean("right reverse limit", RobotMap.liftTalon_Right.isRevLimitSwitchClosed());
        
        
        SmartDashboard.putNumber("pot value", RobotMap.armarm_talon.get());
        SmartDashboard.putNumber("gyro value", RobotMap.driveGyro1.getAngle());        
        SmartDashboard.putNumber("auto encoder value", RobotMap.drivedrive_encoder.getDistance());
        SmartDashboard.putNumber("lift left talon value", RobotMap.liftTalon_Left.get());
    	SmartDashboard.putNumber("lift right talon value", RobotMap.liftTalon_Right.get());
    	
    }
}
